# Generated by Django 4.2 on 2023-09-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default=123, max_length=250, verbose_name='Наим'),
            preserve_default=False,
        ),
    ]
